const API='/api/v1',API_KEY=localStorage.getItem('tinkle_api_key')||'dev-key',VOICE_ID='uju3wxzG5OhpWcoi3SMy';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],actor=$('#tinkleActor'),stage=$('#stage'),statusText=$('#statusText'),modeText=$('#modeText'),coreState=$('#coreState');
const notifications=[];const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function addNotification(title,body){notifications.unshift({title,body,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});notifications.splice(12);$('#notifCount').textContent=notifications.length;$('#notificationsList').innerHTML=notifications.map(n=>`<div class="feed-item"><span class="time">${n.time}</span><b>${esc(n.title)}</b><p>${esc(n.body)}</p></div>`).join('')}
function setState(state){actor.classList.remove('listening','speaking','executing','explaining');if(state!=='ready')actor.classList.add(state);const label={ready:'READY',listening:'LISTENING',speaking:'SPEAKING',executing:'EXECUTING',explaining:'EXPLAINING'}[state]||String(state).toUpperCase();statusText.textContent=label;modeText.textContent=label;coreState.textContent=label;$('#cognitiveState').textContent=label}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json','X-API-Key':API_KEY,...(options.headers||{})}});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json()}
function program(gl,vs,fs){const compile=(t,s)=>{const sh=gl.createShader(t);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh};const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
function resizeCanvas(c,gl){const d=devicePixelRatio||1,r=c.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width*d)),h=Math.max(1,Math.floor(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h}gl.viewport(0,0,c.width,c.height)}
function drawCore(){const c=$('#coreCanvas'),gl=c.getContext('webgl',{antialias:true,alpha:true});if(!gl){addNotification('3D fallback','WebGL is unavailable; Tinkle core cannot render fully.');return}const vs=`attribute vec3 p;uniform float t;uniform float e;uniform float pulse;void main(){vec3 q=p;float w=sin(t*1.7+p.z*10.0+atan(p.y,p.x)*5.0)*.018*e;q*=1.0+w+.025*sin(t*2.2+length(p)*18.0)*pulse;float a=t*.16,cs=cos(a),sn=sin(a);q.xz=mat2(cs,-sn,sn,cs)*q.xz;float pr=1.0/(1.45-q.z*.35);gl_Position=vec4(q.xy*pr,q.z*.42,1.0);gl_PointSize=(1.2+3.2*(1.0-q.z*.5))*pulse;}`;const fs=`precision mediump float;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;gl_FragColor=vec4(.28,1.,.95,(1.-d*2.)*.78);}`;const p=program(gl,vs,fs),a=gl.getAttribLocation(p,'p'),tl=gl.getUniformLocation(p,'t'),el=gl.getUniformLocation(p,'e'),pl=gl.getUniformLocation(p,'pulse'),pts=[];for(let i=0;i<7200;i++){const z=Math.random()*2-1,a0=Math.random()*Math.PI*2,r=Math.sqrt(1-z*z),j=(Math.random()-.5)*.02;pts.push(r*Math.cos(a0)+j,r*Math.sin(a0)+j,z+j)}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pts),gl.STATIC_DRAW);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);function frame(ms){const t=ms/1000;resizeCanvas(c,gl);let e=1,pulse=1;if(actor.classList.contains('listening')){e=1.8;pulse=1.55}else if(actor.classList.contains('speaking')){e=1.45;pulse=1.95}else if(actor.classList.contains('executing')){e=2.05;pulse=2.25}else if(actor.classList.contains('explaining')){e=.78;pulse=.88}gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(p);gl.uniform1f(tl,t);gl.uniform1f(el,e);gl.uniform1f(pl,pulse);gl.drawArrays(gl.POINTS,0,pts.length/3);requestAnimationFrame(frame)}requestAnimationFrame(frame)}
const scene={mode:'auto',rotX:-.2,rotY:.5,zoom:1,drag:false,x:0,y:0,step:0,data:null,raf:0,source:'local',frames:null,frame:0};
const scenes={
 atom:{name:'ATOM / PARTICLE STRUCTURE',steps:['Core structure and surrounding orbital layers.','Particle paths are shown as conceptual visualization, not measured trajectories.','The model remains an explanatory representation.'],labels:['CORE','ORBITAL LAYER','PARTICLE']},
 solar:{name:'SYSTEM / ORBITAL RELATIONSHIPS',steps:['Central body and primary orbital plane.','Bodies are distributed across nested paths for comparison.','The scene is a conceptual system model.'],labels:['CENTER','ORBIT','BODY']},
 circuit:{name:'CIRCUIT / SIGNAL FLOW',steps:['Nodes establish the system topology.','Lines represent conceptual signal paths.','The highlighted route shows flow through the network.'],labels:['INPUT','NODE','OUTPUT']},
 engine:{name:'ENGINE / MECHANISM',steps:['Central mechanism is isolated first.','Radial elements show interacting components.','The scene exposes relationships for explanation.'],labels:['CORE','MECHANISM','OUTPUT']},
 concept:{name:'CONCEPT / SYSTEM MAP',steps:['Tinkle decomposes the topic into a visual structure.','Relationships are represented as connected layers.','Unknown or unverified parts remain labeled as conceptual.'],labels:['CONCEPT','RELATION','UNKNOWN']}
};
function classify(s){s=(s||'').toLowerCase();if(/atom|ذرة|electron|إلكترون|chem|جزيء/.test(s))return'atom';if(/solar|planet|نظام شمسي|كوكب|orbit|مدار/.test(s))return'solar';if(/circuit|دائرة|electric|كهرب|network|شبكة/.test(s))return'circuit';if(/engine|محرك|motor|turbine|توربين|machine|آلة/.test(s))return'engine';return'concept'}
function localScene(text){const mode=scene.mode==='auto'?classify(text):scene.mode,p=[];const add=(x,y,z)=>p.push(x,y,z),line=(a,b,n=80)=>{for(let i=0;i<n;i++){const k=i/(n-1);add(a[0]+(b[0]-a[0])*k,a[1]+(b[1]-a[1])*k,a[2]+(b[2]-a[2])*k)}},ring=(r,tilt=0,n=220)=>{for(let i=0;i<n;i++){const a=i*Math.PI*2/n,z=Math.sin(a)*r;add(Math.cos(a)*r,z*Math.sin(tilt),z*Math.cos(tilt))}},sphere=(r,n=1400)=>{for(let i=0;i<n;i++){const z=Math.random()*2-1,a=Math.random()*6.283,rr=Math.sqrt(1-z*z);add(r*rr*Math.cos(a),r*rr*Math.sin(a),r*z)}};if(mode==='atom'){sphere(.5,1900);ring(.86,.95);ring(.86,-.95)}else if(mode==='solar'){sphere(.18,900);for(let i=1;i<5;i++){const r=.3+i*.23;ring(r)}}else if(mode==='circuit'){for(let i=-3;i<=3;i++){line([-1.3,i*.22,0],[1.3,i*.22,0]);line([i*.4,-.65,0],[i*.4,.65,0])}}else if(mode==='engine'){sphere(.48,1250);ring(.72,.7);ring(.72,-.7)}else{sphere(.5,1550);for(let i=0;i<5;i++)ring(.68+i*.11,(i-2)*.16)}return{title:scenes[mode].name,mode,objects:[{geometry:'points',points:p,material:'points'}],annotations:scenes[mode].labels,source:'LOCAL_FALLBACK'}}
function flattenScene(sc){const out=[];for(const obj of (sc.objects||[])){if(obj.geometry==='mesh'){const v=obj.vertices||[],idx=obj.indices||[];const verts=[];for(const i of idx){verts.push(v[i*3],v[i*3+1],v[i*3+2])}out.push({mode:'triangles',data:new Float32Array(verts),material:obj.material})}else if(obj.geometry==='lines'){const verts=[];for(const seg of (obj.segments||[])){for(const q of seg)verts.push(...q)}out.push({mode:'lines',data:new Float32Array(verts),material:obj.material})}else if(obj.geometry==='points'){out.push({mode:'points',data:new Float32Array(obj.points||[]),material:obj.material})}}return out}
async function fetch3DScene(kind,name,prompt,parameters={}){return api('/visual3d/scene',{method:'POST',body:JSON.stringify({kind,name,prompt,parameters})})}
async function load3DScene(kind,name,prompt,parameters={}){try{const r=await fetch3DScene(kind,name,prompt,parameters);scene.data=r.scene;scene.source=r.provenance?.mode||'SERVER';scene.frame=0;$('#sceneReadout').textContent=`3D MODEL / ${String(r.scene.title||name).toUpperCase()}`;renderLabelsGeneric(r.scene.annotations||[]);drawWebGLScene(r.scene);$('#explainCopy').textContent=(r.scene.description||'Procedural 3D model')+' · '+(r.limitations?.[0]||'');return r}catch(e){addNotification('3D engine fallback',e.message);const local=localScene(prompt||name);scene.data=local;renderLabelsGeneric(local.annotations);drawWebGLScene(local);return {scene:local}}}
function renderLabelsGeneric(labels){$('#sceneLabels').innerHTML=(labels||[]).slice(0,6).map((x,i)=>`<div class="scene-label" style="left:${12+(i%3)*28}%;top:${18+Math.floor(i/3)*30}%">${esc(x)}</div>`).join('')}
function renderLabels(mode){renderLabelsGeneric((scenes[mode]||scenes.concept).labels)}
function drawWebGLScene(sc){const c=$('#explainCanvas'),gl=c.getContext('webgl',{antialias:true,alpha:true});if(!gl)return;cancelAnimationFrame(scene.raf);const batches=flattenScene(sc);const vs=`attribute vec3 p;uniform mat4 m;void main(){gl_Position=m*vec4(p,1.0);gl_PointSize=3.4;}`,fs=`precision mediump float;uniform vec4 color;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;gl_FragColor=color;}`;const prog=program(gl,vs,fs),a=gl.getAttribLocation(prog,'p'),ml=gl.getUniformLocation(prog,'m'),co=gl.getUniformLocation(prog,'color');const buffers=batches.map(b=>{const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,b.data,gl.STATIC_DRAW);return {...b,buf}});const frame=()=>{resizeCanvas(c,gl);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);const rx=scene.rotX,ry=scene.rotY+performance.now()*.00012,sx=Math.sin(rx),cx=Math.cos(rx),sy=Math.sin(ry),cy=Math.cos(ry),z=2.7/scene.zoom;const m=new Float32Array([cy,sy*sx,sy*cx,0,0,cx,-sx,0,-sy,cy*sx,cy*cx,0,0,0,-1/z,1]);gl.useProgram(prog);gl.uniformMatrix4fv(ml,false,m);for(const b of buffers){gl.bindBuffer(gl.ARRAY_BUFFER,b.buf);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);const col=b.material==='cad'?[.2,.85,1,.95]:b.material==='metal'?[.5,.9,1,.92]:b.material==='helix'?[.3,1,.75,.9]:[.28,1,.95,.86];gl.uniform4fv(co,col);gl.drawArrays(b.mode==='triangles'?gl.TRIANGLES:b.mode==='lines'?gl.LINES:gl.POINTS,0,b.data.length/3)}scene.raf=requestAnimationFrame(frame)};frame()}
async function drawExplanation3D(text){const data=await load3DScene('generate','concept',text||'concept');scene.data=data.scene;scene.step=0;updateStep()}
function renderLabels(mode){const labels=(scenes[mode]||scenes.concept).labels;$('#sceneLabels').innerHTML=labels.map((x,i)=>`<div class="scene-label" style="left:${34+i*16}%;top:${32+(i%2)*22}%">${esc(x)}</div>`).join('')}
function drawExplanation3D(text){const c=$('#explainCanvas'),gl=c.getContext('webgl',{antialias:true,alpha:true});if(!gl)return;const data=makeScene(text);scene.data=data;renderLabels(data.mode);$('#sceneReadout').textContent=`3D MODEL / ${data.mode.toUpperCase()}`;const vs=`attribute vec3 p;uniform mat4 m;uniform float pulse;void main(){vec4 q=m*vec4(p,1.0);gl_Position=q;gl_PointSize=2.2+1.1*pulse;}`,fs=`precision mediump float;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;gl_FragColor=vec4(.28,1.,.95,(1.-d*2.)*.86);}`,p=program(gl,vs,fs),a=gl.getAttribLocation(p,'p'),ml=gl.getUniformLocation(p,'m'),pu=gl.getUniformLocation(p,'pulse'),b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data.points,gl.STATIC_DRAW);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);cancelAnimationFrame(scene.raf);const frame=()=>{resizeCanvas(c,gl);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);const rx=scene.rotX,ry=scene.rotY+performance.now()*.00012,z=2.7/scene.zoom,cx=Math.cos(rx),sx=Math.sin(rx),cy=Math.cos(ry),sy=Math.sin(ry);const m=new Float32Array([cy,sy*sx,sy*cx,0,0,cx,-sx,0,-sy,cy*sx,cy*cx,0,0,0,-1/z,1]);gl.useProgram(p);gl.uniformMatrix4fv(ml,false,m);gl.uniform1f(pu,1+.25*Math.sin(performance.now()*.003));gl.drawArrays(gl.POINTS,0,data.points.length/3);scene.raf=requestAnimationFrame(frame)};frame()}
function updateStep(){const data=scenes[scene.data?.mode||'concept']||scenes.concept;const steps=data.steps||['3D scene generated from the active model.','Geometry and relationships are shown for inspection.','Validate domain assumptions before using the result.'];scene.step=Math.max(0,Math.min(steps.length-1,scene.step));$('#stepLabel').textContent=`STEP ${String(scene.step+1).padStart(2,'0')} / ${steps.length}`;$('#explainCopy').textContent=steps[scene.step]}
function showExplanation(title,copy){$('#viewPanel').classList.add('hidden');$('#explainTitle').textContent=title;$('#explainPanel').classList.remove('hidden');actor.classList.add('explaining');setState('explaining');scene.step=0;addNotification('3D explanation started',title);drawExplanation3D(copy);updateStep()}
$('#closeExplain').onclick=()=>{$('#explainPanel').classList.add('hidden');actor.classList.remove('explaining');setState('ready')};
$$('.scene-controls button[data-scene]').forEach(b=>b.onclick=async()=>{scene.mode=b.dataset.scene;$$('.scene-controls button[data-scene]').forEach(x=>x.classList.remove('active'));b.classList.add('active');await load3DScene('generate','concept',$('#explainCopy').textContent||b.dataset.scene);updateStep()});
$$('.scene-controls button[data-tool]').forEach(b=>b.onclick=async()=>{const tool=b.dataset.tool;if(tool==='library'){const key=$('#modelSelect').value||'atom';await load3DScene('library',key,'');}else if(tool==='cad'){const key=$('#cadSelect').value||'box';await load3DScene('cad',key,'',{width:2,height:1,depth:.7,radius:.5,length:1.5,teeth:20,thickness:.2});}else if(tool==='generate'){await load3DScene('generate','concept',$('#scenePrompt').value||'a scientific concept');}else{await run3DPhysics($('#physicsSelect').value||'gravity')}});
$('#run3d').onclick=async()=>{const key=$('#modelSelect').value||'atom';if($('#scenePrompt').value.trim())await load3DScene('generate','concept',$('#scenePrompt').value);else await load3DScene('library',key,'')};
async function load3DCatalog(){try{const r=await api('/visual3d/catalog');$('#modelSelect').innerHTML=r.models.map(m=>`<option value="${esc(m.id)}">${esc(m.title)}</option>`).join('')}catch(e){$('#modelSelect').innerHTML='<option value="atom">ATOM</option>'}}
function physicsFrameScene(kind,frame){let points=[];if(frame.objects)points=frame.objects.map(o=>o.position||[]).flat();else if(frame.field){const n=frame.field.length;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const v=frame.field[y][x];points.push((x-n/2)/(n/2),v*1.5,(y-n/2)/(n/2))}}return{title:`PHYSICS / ${kind.toUpperCase()}`,description:`Time-indexed 3D numerical simulation · t=${Number(frame.t||0).toFixed(3)}`,objects:[{geometry:'points',points,material:'physics'}],annotations:['STATE','TIME','NUMERICAL MODEL'],mode:'concept',steps:['Initial numerical state.','Advance the simulation frame-by-frame.','Results are computational, not experimental evidence.']}}
async function run3DPhysics(kind){try{const r=await api('/visual3d/simulate',{method:'POST',body:JSON.stringify({kind,steps:90,dt:.02,parameters:{}})});scene.frames=r.frames;scene.frame=0;const drawFrame=()=>{const sc=physicsFrameScene(kind,scene.frames[scene.frame]);scene.data=sc;renderLabelsGeneric(sc.annotations);drawWebGLScene(sc);$('#sceneReadout').textContent=`3D PHYSICS / ${kind.toUpperCase()} · FRAME ${scene.frame+1}/${scene.frames.length}`;if(scene.frame<scene.frames.length-1){scene.frame++;setTimeout(drawFrame,40)}};drawFrame();$('#explainCopy').textContent=r.limitations.join(' ')}catch(e){addNotification('Physics error',e.message)}}
$('#prevStep').onclick=()=>{scene.step--;updateStep()};$('#nextStep').onclick=()=>{scene.step++;updateStep()};
function viewCard(title,text,value=''){return`<div class="view-card"><b>${esc(title)}</b><span>${esc(text)}</span>${value?`<div class="mini-bar"><i style="width:${value}%"></i></div>`:''}</div>`}
const views={
 chat:{title:'CHAT / TINKLE CORE',cards:[['ACTIVE SESSION','Talk to Tinkle naturally. Voice and text commands are routed through the current system.'],['3D EXPLANATION','Ask “اشرح…” or “explain…” and Tinkle creates a visual teaching space.'],['VOICE','Configured voice identity: '+VOICE_ID],['STATE','Tinkle changes position, size and visual intensity by state.']]},
 projects:{title:'PROJECTS',cards:[['PROJECT WORKSPACE','Projects can contain goals, files, knowledge, tasks, research, hypotheses, simulations, experiments, decisions, failures and results.'],['CURRENT','No project selected.'],['CONTROL','Project actions remain subject to privacy and permission boundaries.']]},
 knowledge:{title:'KNOWLEDGE',cards:[['KNOWLEDGE ENGINE','Structured knowledge and retrieval surface.'],['PROVENANCE','Important claims can retain source and confidence context.'],['STATUS','Integrated backend surface available.']]},
 research:{title:'RESEARCH',cards:[['PIPELINE','Question → Search → Sources → Evidence → Knowledge → Hypotheses → Analysis → Simulation → Criticism → Verification → Report.'],['BOUNDARY','External web search remains provider-dependent.'],['OUTPUT','Research results remain verification-aware.']]},
 experiments:{title:'EXPERIMENTS',cards:[['CONTROLLED WORKSPACE','Experiment concepts are presented separately from production execution.'],['SAFETY','Dangerous tools remain permission/sandbox gated.'],['RESULTS','Use the Simulation surface when a computational model exists.']]},
 simulation:{title:'SIMULATION',cards:[['PIPELINE','Model → Parameters → Simulation → Results → Visualization → Optimization.'],['3D VIEW','Results can be explained in the holographic 3D workspace.'],['BOUNDARY','No specialized solver is invented where the Blueprint does not specify one.']]},
 agents:{title:'AGENTS',cards:[['MULTI-AGENT','Agent work is surfaced as coordinated system activity.'],['GUARDIAN','Review and permission boundaries remain visible.'],['STATUS','Agent execution is monitored by Tinkle Observer.']]},
 memory:{title:'MEMORY',cards:[['LONG-TERM MEMORY','Memory is exposed as a user-controlled system surface.'],['PRIVACY','Storage can be restricted through Privacy System.'],['LESSONS','Self-evaluation can store appropriate lessons.']]},
 skills:{title:'SKILLS',cards:[['SKILL EVOLUTION','Skills are versioned with procedure, tools, prerequisites, benchmarks, failure modes and confidence.'],['FAILURE ATLAS','Observed failure modes can inform later skill versions.'],['STATUS','Evidence-driven evolution only.']]},
 discoveries:{title:'DISCOVERIES',cards:[['DISCOVERY ENGINE','Cross-domain patterns can be surfaced as discovery candidates.'],['VERIFICATION','Discoveries are not silently promoted to facts.'],['3D','Open the explanation workspace to visualize a concept.']]},
 hypotheses:{title:'HYPOTHESES',cards:[['HYPOTHESIS UNIVERSE','Multiple hypotheses can be generated, tested, rejected, modified, combined and retested.'],['EPISTEMIC STATE','Hypothesis ≠ verified fact.'],['STREAM','Live candidates appear in the right-side discovery stream.']]},
 evidence:{title:'EVIDENCE',cards:[['CLAIM','Claim'],['CHAIN','Evidence → Source → Confidence → Verification'],['EXPLAINABILITY','Users can understand why a result was reached without exposing private model chain-of-thought.']]},
 tasks:{title:'TASKS',cards:[['TASK PIPELINE','Task creation and execution are exposed through the command layer.'],['STATE','Ready → Listening → Executing → Speaking / Explaining.'],['CONTROL','Failures remain visible instead of being silently ignored.']]},
 health:{title:'SYSTEM HEALTH',cards:[['PHASES','Phases 1 → 27 are integrated into this release.'],['OBSERVER','Accuracy, hallucinations, retrieval, memory, latency, loops, failures, drift, resources, tools and security events are monitored when observations exist.'],['SECURITY','Authentication, permissions, audit boundaries and sensitive-tool restrictions are active.']]},
 settings:{title:'SETTINGS',cards:[['PRIVACY','Storage, cloud-model usage, local mode, export and deletion controls.'],['VOICE','Voice ID: '+VOICE_ID+' (configuration metadata; provider connection required for the exact voice).'],['UI','Holographic cyan 3D mode is the current visual reference.']]}
};
function openView(name){const v=views[name]||views.chat;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent=v.title;$('#viewPanel').innerHTML=`<div class="view-head"><div><span class="eyebrow">TINKLE MODULE</span><h2>${esc(v.title)}</h2></div><button class="ghost" id="viewClose">×</button></div><div class="view-grid">${v.cards.map(c=>viewCard(c[0],c[1],c[2]||'')).join('')}</div>`;$('#viewPanel').classList.remove('hidden');$('#viewClose').onclick=()=>$('#viewPanel').classList.add('hidden');addNotification('Module opened',v.title);if(name==='chat')$('#viewPanel').classList.add('hidden')}
$$('.nav-item').forEach(b=>b.onclick=()=>openView(b.dataset.view));
$('#commandMic').onclick=()=>{const b=$('#commandMic');if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){addNotification('Voice input unavailable','Speech recognition is not available in this browser.');return}if(b._rec){b._rec.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-US';r.interimResults=false;b._rec=r;b.classList.add('active');setState('listening');r.onresult=e=>{$('#commandInput').value=e.results[0][0].transcript;sendCommand()};r.onend=()=>{b.classList.remove('active');b._rec=null;if(statusText.textContent==='LISTENING')setState('ready')};r.onerror=()=>addNotification('Voice input error','Speech recognition stopped.');r.start()};
async function sendCommand(){const input=$('#commandInput'),text=input.value.trim();if(!text)return;setState('executing');addNotification('Task received',text);if(/explain|اشرح|شرح|show me|وريني|فسر/i.test(text)){showExplanation('Interactive 3D explanation',text);setTimeout(()=>speakBrowser('I will explain this visually, Doctor.'),700);return}try{const t=await api('/tasks',{method:'POST',body:JSON.stringify({title:text,description:text,prompt:text})});addNotification('Task created','Tinkle registered the task.');if(t.task?.id)await api(`/tasks/${t.task.id}/run`,{method:'POST'}).catch(()=>null);speakBrowser('Yes, Doctor.')}catch(e){addNotification('Execution boundary',e.message);setState('ready')}}
function speakBrowser(text){if(!('speechSynthesis'in window)){addNotification('TTS unavailable','Browser speech synthesis is unavailable.');return}const u=new SpeechSynthesisUtterance(text);u.rate=.9;u.pitch=.85;u.volume=1;u.onstart=()=>setState('speaking');u.onend=()=>setState('ready');speechSynthesis.cancel();speechSynthesis.speak(u)}
$('#sendCommand').onclick=sendCommand;$('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendCommand()});$('#speakBtn').onclick=()=>speakBrowser('Yes, Doctor.');$('#listenBtn').onclick=()=>$('#commandMic').click();$('#focusBtn').onclick=()=>showExplanation('Tinkle visual workspace','Tinkle yields the stage and opens a live 3D teaching space.');
async function refreshObserver(){try{const d=await api('/observer/snapshot'),m=d.metrics||d.data||d;$('#accuracy').textContent=m.accuracy??'—';$('#latency').textContent=m.latency_ms?`${m.latency_ms}ms`:'—';$('#latencyState').textContent=m.latency_ms?`${m.latency_ms}ms`:'—'}catch(e){}}
function refreshHypotheses(){$('#hypotheses').innerHTML='<div class="hypothesis"><small>DISCOVERY</small><strong>Live hypothesis stream</strong><p>New candidates appear here as Tinkle generates, tests and verifies them.</p></div><div class="hypothesis"><small>STATUS</small><strong>Verification-aware</strong><p>Unverified discoveries remain clearly marked.</p></div>'}
function seedAchievements(){const items=[['27','Complete UI / holographic 3D'],['26','Privacy System online'],['25','Security hardening active'],['24','Controlled self-improvement gated'],['23','Observer monitoring active'],['22','Self-evaluation active'],['21','Skill evolution versioned']];$('#achievements').innerHTML=items.map(([n,t])=>`<div class="achievement"><span class="mark">◈</span><div><b>PHASE ${n} — ${t}</b><small>Integrated into Tinkle</small></div></div>`).join('')}
let drag={active:false,x:0,y:0,left:0,top:0};actor.addEventListener('pointerdown',e=>{if(actor.classList.contains('explaining'))return;drag.active=true;actor.setPointerCapture(e.pointerId);const r=actor.getBoundingClientRect(),s=stage.getBoundingClientRect();drag.x=e.clientX;drag.y=e.clientY;drag.left=r.left-s.left;drag.top=r.top-s.top;actor.style.left=`${drag.left+r.width/2}px`;actor.style.top=`${drag.top+r.height/2}px`;actor.style.transform='translate(-50%,-50%)'});actor.addEventListener('pointermove',e=>{if(!drag.active)return;const s=stage.getBoundingClientRect(),r=actor.getBoundingClientRect(),nx=Math.max(r.width/2,Math.min(s.width-r.width/2,drag.left+r.width/2+e.clientX-drag.x)),ny=Math.max(r.height/2,Math.min(s.height-r.height/2,drag.top+r.height/2+e.clientY-drag.y));actor.style.left=`${nx}px`;actor.style.top=`${ny}px`});actor.addEventListener('pointerup',()=>drag.active=false);actor.addEventListener('pointercancel',()=>drag.active=false);
$('#explainCanvas').addEventListener('pointerdown',e=>{scene.drag=true;scene.x=e.clientX;scene.y=e.clientY});window.addEventListener('pointermove',e=>{if(!scene.drag)return;scene.rotY+=(e.clientX-scene.x)*.006;scene.rotX+=(e.clientY-scene.y)*.006;scene.x=e.clientX;scene.y=e.clientY});window.addEventListener('pointerup',()=>scene.drag=false);$('#explainCanvas').addEventListener('wheel',e=>{e.preventDefault();scene.zoom=Math.max(.65,Math.min(1.8,scene.zoom-e.deltaY*.001))},{passive:false});
function init(){drawCore();load3DCatalog();seedAchievements();refreshHypotheses();addNotification('Tinkle online','Complete holographic UI initialized.');addNotification('Voice identity loaded',`Voice ID: ${VOICE_ID}`);refreshObserver();setInterval(refreshObserver,5000)}init();
