from __future__ import annotations

import math

from tinkle.engineering_engine.schemas import (
    EngineeringDomain,
    EngineeringModule,
    EngineeringRequest,
    EngineeringResult,
    EngineeringSolveRequest,
)


class EngineeringEngine:
    """Phase 15 boundary for the nine engineering modules named by the Blueprint.

    The Blueprint defines the engineering domains but does not specify design
    algorithms, engineering databases, simulation solvers, or evidence
    providers. This boundary therefore performs deterministic module
    selection without fabricating an engineering solution.
    """

    _MODULES = {
        EngineeringDomain.mechanical_engineering: EngineeringModule(
            domain=EngineeringDomain.mechanical_engineering,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.electrical_engineering: EngineeringModule(
            domain=EngineeringDomain.electrical_engineering,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.electronics: EngineeringModule(
            domain=EngineeringDomain.electronics,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.robotics: EngineeringModule(
            domain=EngineeringDomain.robotics,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.control_systems: EngineeringModule(
            domain=EngineeringDomain.control_systems,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.thermal_engineering: EngineeringModule(
            domain=EngineeringDomain.thermal_engineering,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.materials_engineering: EngineeringModule(
            domain=EngineeringDomain.materials_engineering,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.energy_systems: EngineeringModule(
            domain=EngineeringDomain.energy_systems,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
        EngineeringDomain.software_engineering: EngineeringModule(
            domain=EngineeringDomain.software_engineering,
            status="BOUNDARY_READY",
            capabilities=["domain routing", "structured problem intake", "deterministic engineering models"],
        ),
    }

    def inspect(self, request: EngineeringRequest) -> EngineeringResult:
        module = self._MODULES[request.domain]
        return EngineeringResult(
            problem=request.problem.strip(),
            domain=request.domain,
            status="MODULE_READY",
            module=module,
            solution=None,
            requirements=[],
            limitations=[
                "The Blueprint names the engineering modules but does not specify engineering design algorithms, databases, simulation solvers, or evidence providers.",
                "No engineering solution is generated by this boundary without the appropriate future model, calculation, simulation, or evidence provider.",
            ],
        )

    def solve(self, request: EngineeringSolveRequest) -> EngineeringResult:
        inputs = self._validate_inputs(request.inputs)
        solvers = {
            (EngineeringDomain.mechanical_engineering, "axial_stress_v1"): self._axial_stress,
            (EngineeringDomain.mechanical_engineering, "beam_deflection_v1"): self._beam_deflection,
            (EngineeringDomain.electrical_engineering, "ohms_law_v1"): self._ohms_law,
            (EngineeringDomain.electrical_engineering, "capacitor_energy_v1"): self._capacitor_energy,
            (EngineeringDomain.electronics, "rc_time_constant_v1"): self._rc_time_constant,
            (EngineeringDomain.electronics, "voltage_divider_v1"): self._voltage_divider,
            (EngineeringDomain.robotics, "planar_motion_v1"): self._planar_motion,
            (EngineeringDomain.robotics, "torque_v1"): self._torque,
            (EngineeringDomain.control_systems, "first_order_step_v1"): self._first_order_step,
            (EngineeringDomain.control_systems, "second_order_natural_frequency_v1"): self._second_order_natural_frequency,
            (EngineeringDomain.thermal_engineering, "conduction_v1"): self._conduction,
            (EngineeringDomain.thermal_engineering, "convection_v1"): self._convection,
            (EngineeringDomain.materials_engineering, "axial_stress_v1"): self._axial_stress,
            (EngineeringDomain.materials_engineering, "thermal_expansion_v1"): self._thermal_expansion,
            (EngineeringDomain.energy_systems, "power_efficiency_v1"): self._power_efficiency,
            (EngineeringDomain.energy_systems, "battery_capacity_v1"): self._battery_capacity,
            (EngineeringDomain.software_engineering, "throughput_v1"): self._throughput,
            (EngineeringDomain.software_engineering, "littles_law_v1"): self._littles_law,
        }
        solver = solvers.get((request.domain, request.model))
        if solver is None:
            raise ValueError(f"Unsupported engineering model: {request.domain.value}/{request.model}")
        outputs, assumptions = solver(inputs)
        if any(not math.isfinite(float(v)) for v in outputs.values()):
            raise ValueError("Engineering result contains a non-finite value")
        module = self._MODULES[request.domain].model_copy(update={"status": "CALCULATED"})
        return EngineeringResult(
            problem=request.problem.strip(), domain=request.domain, status="CALCULATED", module=module,
            solution=", ".join(f"{k}={v:.12g}" for k, v in outputs.items()),
            calculation={"model": request.model, "inputs": inputs, "outputs": outputs, "assumptions": assumptions, "evidence_required": True},
            requirements=[],
            limitations=["Deterministic engineering model result; real design requires domain constraints, material/device data, standards, simulation and validation.", "Calculation is not experimental evidence."],
        )

    @staticmethod
    def _validate_inputs(inputs: dict[str, float]) -> dict[str, float]:
        if len(inputs) > 32:
            raise ValueError("Too many inputs")
        out: dict[str, float] = {}
        for name, value in inputs.items():
            if not isinstance(name, str) or not name.isidentifier() or name.startswith("_"):
                raise ValueError(f"Invalid input name: {name!r}")
            if not isinstance(value, (int, float)) or not math.isfinite(float(value)):
                raise ValueError(f"Input {name!r} must be finite")
            out[name] = float(value)
        return out

    @staticmethod
    def _req(i: dict[str, float], *names: str) -> list[float]:
        return [i[n] for n in names]

    @staticmethod
    def _axial_stress(i):
        force, area = EngineeringEngine._req(i, "force_n", "area_m2")
        if area <= 0: raise ValueError("area_m2 must be positive")
        return {"stress_pa": force / area}, ["Uniform axial load over the stated area."]

    @staticmethod
    def _ohms_law(i):
        voltage = i.get("voltage_v"); current = i.get("current_a"); resistance = i.get("resistance_ohm")
        supplied = sum(x is not None for x in (voltage, current, resistance))
        if supplied != 2: raise ValueError("Provide exactly two of voltage_v, current_a, resistance_ohm")
        if voltage is None: voltage = current * resistance
        elif current is None:
            if resistance == 0: raise ValueError("resistance_ohm must be non-zero")
            current = voltage / resistance
        else: resistance = voltage / current if current != 0 else (_ for _ in ()).throw(ValueError("current_a must be non-zero"))
        return {"voltage_v": voltage, "current_a": current, "resistance_ohm": resistance, "power_w": voltage * current}, ["DC lumped resistive model."]

    @staticmethod
    def _rc_time_constant(i):
        r, c = EngineeringEngine._req(i, "resistance_ohm", "capacitance_f")
        if r < 0 or c <= 0: raise ValueError("resistance_ohm must be non-negative and capacitance_f positive")
        return {"time_constant_s": r * c}, ["First-order RC lumped model."]

    @staticmethod
    def _planar_motion(i):
        x0,y0,vx,vy,t=EngineeringEngine._req(i,"x0_m","y0_m","vx_m_s","vy_m_s","time_s")
        return {"x_m":x0+vx*t,"y_m":y0+vy*t,"speed_m_s":math.hypot(vx,vy)}, ["Constant planar velocity; no acceleration."]

    @staticmethod
    def _first_order_step(i):
        tau, gain, t, amplitude = EngineeringEngine._req(i,"time_constant_s","gain","time_s","input_amplitude")
        if tau <= 0: raise ValueError("time_constant_s must be positive")
        return {"output": gain*amplitude*(1-math.exp(-t/tau))}, ["Stable first-order linear system with zero initial condition."]

    @staticmethod
    def _conduction(i):
        k, area, delta_t, length = EngineeringEngine._req(i,"conductivity_w_mk","area_m2","delta_temperature_k","length_m")
        if k < 0 or area <= 0 or length <= 0: raise ValueError("conductivity must be non-negative; area and length positive")
        return {"heat_rate_w": k*area*delta_t/length}, ["Steady one-dimensional conduction through uniform material."]

    @staticmethod
    def _power_efficiency(i):
        useful, input_power = EngineeringEngine._req(i,"useful_power_w","input_power_w")
        if input_power <= 0: raise ValueError("input_power_w must be positive")
        return {"efficiency": useful/input_power,"efficiency_percent":100*useful/input_power}, ["Useful/input power ratio defines efficiency."]

    @staticmethod
    def _throughput(i):
        work, seconds = EngineeringEngine._req(i,"completed_items","elapsed_seconds")
        if seconds <= 0: raise ValueError("elapsed_seconds must be positive")
        return {"items_per_second": work/seconds}, ["Throughput is completed items divided by elapsed time."]

    @staticmethod
    def _beam_deflection(i):
        force, length, e_modulus, moment_of_inertia = EngineeringEngine._req(i, "force_n", "length_m", "elastic_modulus_pa", "moment_of_inertia_m4")
        if e_modulus <= 0 or moment_of_inertia <= 0 or length <= 0:
            raise ValueError("length_m, elastic_modulus_pa and moment_of_inertia_m4 must be positive")
        return {"deflection_m": force * length**3 / (48 * e_modulus * moment_of_inertia)}, ["Simply supported beam with a central point load; linear-elastic, small deflection."]

    @staticmethod
    def _capacitor_energy(i):
        capacitance, voltage = EngineeringEngine._req(i, "capacitance_f", "voltage_v")
        if capacitance < 0:
            raise ValueError("capacitance_f must be non-negative")
        return {"energy_j": 0.5 * capacitance * voltage**2}, ["Ideal capacitor, fully charged to the stated voltage."]

    @staticmethod
    def _voltage_divider(i):
        v_in, r1, r2 = EngineeringEngine._req(i, "input_voltage_v", "resistance1_ohm", "resistance2_ohm")
        if r1 + r2 <= 0:
            raise ValueError("resistance1_ohm + resistance2_ohm must be positive")
        return {"output_voltage_v": v_in * r2 / (r1 + r2)}, ["Unloaded ideal resistive voltage divider."]

    @staticmethod
    def _torque(i):
        force, radius = EngineeringEngine._req(i, "force_n", "radius_m")
        angle_deg = i.get("angle_deg", 90.0)
        return {"torque_n_m": force * radius * math.sin(math.radians(angle_deg))}, ["Rigid lever arm; force applied at the stated angle to the arm."]

    @staticmethod
    def _second_order_natural_frequency(i):
        stiffness, mass = EngineeringEngine._req(i, "stiffness_n_per_m", "mass_kg")
        damping = i.get("damping_n_s_per_m", 0.0)
        if stiffness <= 0 or mass <= 0:
            raise ValueError("stiffness_n_per_m and mass_kg must be positive")
        wn = math.sqrt(stiffness / mass)
        zeta = damping / (2 * math.sqrt(stiffness * mass))
        return {"natural_frequency_rad_s": wn, "damping_ratio": zeta}, ["Linear mass-spring-damper, lumped parameters."]

    @staticmethod
    def _convection(i):
        h_coeff, area, delta_t = EngineeringEngine._req(i, "convection_coefficient_w_m2k", "area_m2", "delta_temperature_k")
        if h_coeff < 0 or area <= 0:
            raise ValueError("convection_coefficient_w_m2k must be non-negative and area_m2 positive")
        return {"heat_rate_w": h_coeff * area * delta_t}, ["Newton's law of cooling; uniform surface temperature and coefficient."]

    @staticmethod
    def _thermal_expansion(i):
        alpha, length, delta_t = EngineeringEngine._req(i, "expansion_coefficient", "length_m", "delta_temperature_k")
        if length <= 0:
            raise ValueError("length_m must be positive")
        return {"delta_length_m": alpha * length * delta_t}, ["Linear thermal expansion of an isotropic solid over a small temperature range."]

    @staticmethod
    def _battery_capacity(i):
        amp_hours, voltage = EngineeringEngine._req(i, "amp_hours", "voltage_v")
        return {"energy_wh": amp_hours * voltage}, ["Nominal energy at rated voltage; ignores discharge-rate and temperature effects."]

    @staticmethod
    def _littles_law(i):
        arrival_rate, wait_time = EngineeringEngine._req(i, "arrival_rate_per_s", "average_wait_time_s")
        if arrival_rate < 0 or wait_time < 0:
            raise ValueError("arrival_rate_per_s and average_wait_time_s must be non-negative")
        return {"average_items_in_system": arrival_rate * wait_time}, ["Little's Law for a stable queue/system in steady state."]

    def modules(self) -> list[EngineeringModule]:
        return list(self._MODULES.values())
